# Service URLs
json.service.url=${JSON_SERVICE_URL}
soap.service.url=${SOAP_SERVICE_URL}
file.service.url=${FILE_SERVICE_URL}

# Upstash Redis REST API
upstash.redis.url=${UPSTASH_REDIS_REST_URL}
upstash.redis.token=${UPSTASH_REDIS_REST_TOKEN}

# Port
server.port=8080

# File Upload Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB